name: build-readme
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '00 01 * * *'
jobs:
  build-starred:
    runs-on: ubuntu-latest
    steps:
    - name: "repository checkout"
      uses: actions/checkout@v4
    - name: "python setup"
      uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: "env requirements"
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
    - name: "run starred"
      run: |
        pip3 install --no-cache starred
        starred \
          --username eagleusb \
          --token ${{ secrets.GITHUB_TOKEN }} \
          --repository awesome-repositories \
          --sort \
          --message 'chore(ci) automated update'
